// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateOrderResponse struct {
	ID   *string `json:"id,omitempty"`
	Succ bool    `json:"Succ"`
}

type EmptyResponse struct {
	Result bool `json:"result"`
}

type NewOrder struct {
	UserID   int                  `json:"userId"`
	Products []*NewProductRequest `json:"products"`
}

type NewProduct struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       int    `json:"price"`
}

type NewProductRequest struct {
	ID    int `json:"id"`
	Count int `json:"count"`
}

type Order struct {
	ID       string            `json:"id"`
	UserID   int               `json:"userId"`
	Products []*ProductRequest `json:"products"`
}

type Product struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       int    `json:"price"`
	Avaliable   *bool  `json:"avaliable,omitempty"`
}

type ProductList struct {
	Products []*Product `json:"products"`
	Count    int        `json:"count"`
}

type ProductRequest struct {
	ID    int `json:"id"`
	Count int `json:"count"`
}

type UpdatedProduct struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       int    `json:"price"`
}
