server:
  port: 8080
postgres:
  host: "localhost"
  port: 5432
  name: "products"
  user: "miha3009"
  password: "pass"
redis:
  host: "localhost"
  port: 6379
inventory:
  host: "localhost"
  port: 8081
